# Generated by Django 4.2.7 on 2023-11-14 08:47

import Catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link_to_file',
            field=models.FileField(blank=True, null=True, upload_to=Catalog.models.book_directory_path),
        ),
    ]
