# Generated by Django 4.2.7 on 2023-11-17 06:38

import Catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_author_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Catalog.models.author_media_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Catalog.models.book_directory_path),
        ),
    ]
