# Generated by Django 4.2.7 on 2023-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0006_rename_description_book_about_alter_author_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
    ]
