# Generated by Django 4.2.7 on 2023-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0007_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='django-db-models-fields-charfield', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, default='django-db-models-fields-charfield-django-db-models-fields-charfield', max_length=200),
        ),
    ]
