# Generated by Django 4.2.7 on 2023-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0008_book_slug_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='django-db-models-fields-charfield-django-db-models-fields-charfield', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='django-db-models-fields-charfield', max_length=200, unique=True),
        ),
    ]
