# Generated by Django 4.2.7 on 2023-11-24 13:15

import Catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0009_alter_author_slug_alter_book_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['genre'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Об авторе'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Catalog.models.author_media_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.TextField(max_length=1000, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalog.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='Catalog.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Catalog.models.book_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='link_to_file',
            field=models.FileField(blank=True, null=True, upload_to=Catalog.models.book_directory_path, verbose_name='Путь до файла'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Жанр'),
        ),
    ]
