# Generated by Django 4.2.7 on 2023-11-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0011_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='django-db-models-fields-charfield', max_length=200, unique=True),
        ),
    ]
