# Generated by Django 4.2.7 on 2023-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0014_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Жанр'),
        ),
    ]
