# Generated by Django 4.2.7 on 2023-12-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0016_bookshelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='books',
            new_name='book',
        ),
    ]
