# Generated by Django 4.2.7 on 2023-12-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_photo_alter_user_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='image',
        ),
    ]
